# texts.py

LANGUAGES = {
    'ru': {
        'start': "Привет!\n\nВыбери действие в меню ниже.",
        'about': "QorQan: это сервис поддержки, созданный в партнерстве с профильными организациями.\n\nЕсли ты столкнулся с домашним насилием, буллингом или любыми проблемами, ты можешь написать нам. Мы здесь, чтобы выслушать и поддержать тебя.",
        'lang_select': "Пожалуйста, выбери язык общения:",
        'tips': "Полезные советы для твоей безопасности:\n\n1. Сохраняй доказательства: делай скриншоты переписок и фото.\n2. Если тебе страшно дома: постарайся уйти в людное место (магазин, аптека, библиотека).\n3. Не вини себя: ты имеешь право на защиту и помощь.\n4. Если есть прямая угроза жизни: звони по номеру 102.",
        'urgency': "🚨 Тебе прямо сейчас угрожает физическая опасность?",
        'wait': "Ищем свободного специалиста QorQan...\n\n⏱ Примерное время ожидания: ~{wait_time}.",
        'no_operators': "⚠️ Внимание: Сейчас нет операторов онлайн. Ответ придет позже, когда кто-то из волонтеров зайдет в систему.",
        'wait_block': "⏳ Оператор еще не подключился. Пожалуйста, подожди немного или отвлекись на игру.",
        'chat_closed_kid': "Ты завершил(а) диалог. Береги себя! Мы всегда рядом, если понадобимся снова.",
        'chat_closed_op': "Оператор завершил диалог. Надеемся, мы смогли тебе помочь!",
        'chat_accepted': "✅ Специалист QorQan подключился. Теперь ты можешь писать сюда.",
        'already_waiting': "У тебя уже есть открытая заявка. Пожалуйста, дождись ответа.",
        'already_active': "Ты уже находишься в активном чате.",
        'cancel_success': "Твоя заявка успешно отменена.",
        # Кнопки меню
        'btn_about': "📋 О QorQan",
        'btn_lang': "🛠️ Язык",
        'btn_tips': "🆘 Помощь",
        'btn_chat': "💬 Оператор",
        'btn_danger': "🚨 Да, угрожает",
        'btn_safe': "✅ Нет, я в безопасности",
        'btn_not_sure': "🤷 Не уверен(а)",
        'btn_cancel': "🔙 Отмена",
        'btn_close': "❌ Завершить диалог",
        'btn_game': "🎮 Мини-игра",
        'btn_cancel_wait': "❌ Отменить заявку",
        'time_3': "3 минуты",
        'time_5': "5 минут",
        'time_10': "10 минут",
        'time_unknown': "неизвестно",
        'banned': "🚫 Ваш аккаунт был ограничен. Если это ошибка, свяжитесь с администрацией."
    },
    'kz': {
        'start': "Сәлем!\n\nТөмендегі мәзірден қажетті әрекетті таңдаңыз.",
        'about': "QorQan: бұл бейінді ұйымдармен серіктестікте құрылған қолдау көрсету сервисі.\n\nЕгер сен үй ішіндегі зорлық-зомбылыққа, буллингке немесе кез келген қиындыққа тап болсаң, бізге жаза аласың. Біз сені тыңдауға дайынбыз.",
        'lang_select': "Тілді таңдаңыз:",
        'tips': "Қауіпсіздікке арналған пайдалы кеңестер:\n\n1. Дәлелдерді сақтаңыз: хаттарды скриншотқа түсіріп алыңыз.\n2. Үйде болу қауіпті болса: адам көп жиналатын жерге (дүкен, кітапхана) барыңыз.\n3. Өзіңді кінәлама: сенің қорғалуға құқығың бар.\n4. Өміріңе қауіп төнсе: 102 нөміріне хабарлас.",
        'urgency': "🚨 Саған дәл қазір физикалық қауіп төніп тұр ма?",
        'wait': "QorQan маманын іздестірудеміз...\n\n⏱ Күту уақыты: ~{wait_time}.",
        'no_operators': "⚠️Назар аударыңыз: Қазір онлайн операторлар жоқ. Жауап еріктілер жүйеге кіргенде беріледі.",
        'wait_block': "⏳ Оператор әлі қосылмады. Күте тұрыңыз немесе ойын ойнаңыз.",
        'chat_closed_kid': "Сен диалогты аяқтадың. Өзіңді сақта! Қажет болсақ, біз әрқашан осындамыз.",
        'chat_closed_op': "Оператор диалогты аяқтады. Көмектесе алдық деп үміттенеміз!",
        'chat_accepted': "✅ QorQan маманы қосылды. Енді осында жаза аласың.",
        'already_waiting': "Сенде ашық өтінім бар. Жауапты күте тұрыңыз.",
        'already_active': "Сен қазір оператормен сөйлесіп жатырсың.",
        'cancel_success': "Өтінімің жойылды.",
        'btn_about': "📋 QorQan туралы",
        'btn_lang': "🛠️ Тіл таңдау",
        'btn_tips': "🆘 Кеңестер",
        'btn_chat': "💬 Оператормен байланыс",
        'btn_danger': "🚨 Иә, қауіп бар",
        'btn_safe': "✅ Жоқ, қауіпсіз жердемін",
        'btn_not_sure': "🤷 Сенімді емеспін",
        'btn_cancel': "🔙 Болдырмау",
        'btn_close': "❌ Диалогты аяқтау",
        'btn_game': "🎮 Ойын ойнау",
        'btn_cancel_wait': "❌ Өтінімді жою",
        'time_3': "3 минут",
        'time_5': "5 минут",
        'time_10': "10 минут",
        'time_unknown': "белгісіз",
        'banned': "🚫 Сіздің аккаунтыңыз бұғатталды. Егер бұл қате болса, әкімшіге хабарласыңыз."
    },
    'en': {
        'start': "Hello!\n\nChoose an action from the menu below.",
        'about': "QorQan: is a support service created in partnership with specialized organizations.\n\nIf you are facing domestic violence, bullying, or any other problems, you can reach out to us. We are here to listen and support you.",
        'lang_select': "Please choose your language:",
        'tips': "Safety advice for you:\n\n1. Keep evidence: take screenshots of messages and photos.\n2. If you feel unsafe at home: try to go to a public place like a store, pharmacy, or library.\n3. Don't blame yourself: you have the right to be safe and get help.\n4. If there is immediate danger: call 102 or your local emergency services.",
        'urgency': "🚨 Are you in immediate physical danger?",
        'wait': "Looking for a QorQan specialist...\n\n⏱ Estimated wait time: ~{wait_time}.",
        'no_operators': "⚠️ Notice: No operators are online right now. Your request will be answered once a volunteer logs in.",
        'wait_block': "⏳ Operator hasn't connected yet. Please wait a moment or try the mini-game.",
        'chat_closed_kid': "You closed the chat. Take care! We are always here if you need us again.",
        'chat_closed_op': "The operator closed the chat. We hope we could help!",
        'chat_accepted': "✅ A QorQan specialist has joined. You can now type here.",
        'already_waiting': "You already have a pending request. Please wait for a response.",
        'already_active': "You are already in an active chat.",
        'cancel_success': "Your request has been canceled.",
        'btn_about': "📋 About QorQan",
        'btn_lang': "🛠️ Language",
        'btn_tips': "🆘 Help & Tips",
        'btn_chat': "💬 Contact Operator",
        'btn_danger': "🚨 Yes, I'm in danger",
        'btn_safe': "✅ No, I am safe",
        'btn_not_sure': "🤷 Not sure",
        'btn_cancel': "🔙 Cancel",
        'btn_close': "❌ End Chat",
        'btn_game': "🎮 Play Game",
        'btn_cancel_wait': "❌ Cancel Request",
        'time_3': "3 minutes",
        'time_5': "5 minutes",
        'time_10': "10 minutes",
        'time_unknown': "unknown",
        'banned': "🚫 Your account has been restricted. If you believe this is an error, please contact an administrator."
    }
}