# texts.py

LANGUAGES = {
    'ru': {
        'start': "Привет!\n\nВыбери действие в меню ниже.",
        'about': "*Мы анонимный сервис помощи подросткам.*\n\nЕсли ты столкнулся с домашним насилием, буллингом или любыми проблемами и тебе нужна помощь, ты можешь написать нам. Мы постараемся поддержать тебя в трудную минуту.",
        'lang_select': "Пожалуйста, выберите язык общения:",
        'tips': "Помни: ты не виноват(а) в том, что происходит.",
        'urgency': "🚨 **Тебе прямо сейчас угрожает физическая опасность?**",
        'wait': "Ищем свободного специалиста...\n\n⏱ Примерное время ожидания: **~{wait_time}**.",
        'no_operators': "⚠️ **Внимание:** Сейчас нет операторов онлайн. Ответ придет позже.",
        'wait_block': "⏳ Оператор еще не подключился. Пожалуйста, подожди.",
        'chat_closed_kid': "Ты завершил(а) диалог. Береги себя!",
        'chat_closed_op': "Оператор завершил диалог. Надеемся, мы помогли!",
        'chat_accepted': "✅ Специалист подключился. Теперь вы можете писать сюда.",
        'already_waiting': "У тебя уже есть открытая заявка.",
        'already_active': "Ты уже в активном чате.",
        'cancel_success': "Твоя заявка отменена.",
        # Кнопки меню
        'btn_about': "📋 О нас",
        'btn_lang': "🛠️ Язык",
        'btn_tips': "🆘 Помощь",
        'btn_chat': "💬 Оператор",
        'btn_danger': "🚨 Да, угрожает",
        'btn_safe': "✅ Нет, я в безопасности",
        'btn_not_sure': "🤷 Не уверен(а)",
        'btn_cancel': "🔙 Отмена",
        'btn_close': "❌ Завершить диалог",
        'btn_game': "🎮 Мини-игра",
        'btn_cancel_wait': "❌ Отменить заявку",
        'time_3': "3 минуты",
        'time_5': "5 минут",
        'time_10': "10 минут",
        'time_unknown': "неизвестно",
        'banned': "🚫 Ваш аккаунт был заблокирован. Если вы считаете это ошибкой, обратитесь к администратору."
    },
    'kz': {
        'start': "Сәлем!\n\nТөмендегі мәзірден қажетті әрекетті таңдаңыз.",
        'about': "Біз — жасөспірімдерге арналған анонимді көмек көрсету сервисіміз.",
        'lang_select': "Тілді таңдаңыз:",
        'tips': "Есіңде болсын: болған жағдайға сен кінәлі емессің.",
        'urgency': "🚨 **Саған дәл қазір физикалық қауіп төніп тұр ма?**",
        'wait': "Маман іздестірудеміз...\n\n⏱ Күту уақыты: **~{wait_time}**.",
        'no_operators': "⚠️ **Назар аударыңыз:** Қазір онлайн операторлар жоқ. Жауап сәл кешірек келеді.",
        'wait_block': "⏳ Оператор әлі қосылмады. Күте тұрыңыз.",
        'chat_closed_kid': "Сен диалогты аяқтадың. Өзіңді сақта!",
        'chat_closed_op': "Оператор диалогты аяқтады. Көмектесе алдық деп үміттенеміз!",
        'chat_accepted': "✅ Маман қосылды. Енді осында жаза аласың.",
        'already_waiting': "Сенде ашық өтінім бар.",
        'already_active': "Сен қазір оператормен сөйлесіп жатырсың.",
        'cancel_success': "Өтінімің жойылды.",
        'btn_about': "📋 Біз туралы",
        'btn_lang': "🛠️ Тіл таңдау",
        'btn_tips': "🆘 Кеңестер",
        'btn_chat': "💬 Оператормен байланыс",
        'btn_danger': "🚨 Иә, қауіп бар",
        'btn_safe': "✅ Жоқ, қауіпсіз жердемін",
        'btn_not_sure': "🤷 Сенімді емеспін",
        'btn_cancel': "🔙 Болдырмау",
        'btn_close': "❌ Диалогты аяқтау",
        'btn_game': "🎮 Ойын ойнау",
        'btn_cancel_wait': "❌ Өтінімді жою",
        'time_3': "3 минут",
        'time_5': "5 минут",
        'time_10': "10 минут",
        'time_unknown': "белгісіз",
        'banned': "🚫 Сіздің аккаунтыңыз бұғатталды. Егер бұл қате болса, әкімшіге хабарласыңыз."
    },
    'en': {
        'start': "Hello!\n\nChoose an action from the menu below.",
        'about': "We are an anonymous support service for teenagers.",
        'lang_select': "Please choose your language:",
        'tips': "Remember: what is happening is not your fault.",
        'urgency': "🚨 **Are you in immediate physical danger?**",
        'wait': "Looking for an available specialist...\n\n⏱ Estimated wait time: **~{wait_time}**.",
        'no_operators': "⚠️ **Notice:** No operators are online right now. Your request will be answered later.",
        'wait_block': "⏳ Operator hasn't connected yet. Please wait.",
        'chat_closed_kid': "You closed the chat. Take care!",
        'chat_closed_op': "The operator closed the chat. We hope we could help!",
        'chat_accepted': "✅ A specialist has joined. You can now type here.",
        'already_waiting': "You already have a pending request.",
        'already_active': "You are already in an active chat.",
        'cancel_success': "Your request has been canceled.",
        'btn_about': "📋 About Us",
        'btn_lang': "🛠️ Language",
        'btn_tips': "🆘 Help & Tips",
        'btn_chat': "💬 Contact Operator",
        'btn_danger': "🚨 Yes, I'm in danger",
        'btn_safe': "✅ No, I am safe",
        'btn_not_sure': "🤷 Not sure",
        'btn_cancel': "🔙 Cancel",
        'btn_close': "❌ End Chat",
        'btn_game': "🎮 Play Game",
        'btn_cancel_wait': "❌ Cancel Request",
        'time_3': "3 minutes",
        'time_5': "5 minutes",
        'time_10': "10 minutes",
        'time_unknown': "unknown",
        'banned': "🚫 Your account has been restricted. If you believe this is an error, please contact an administrator."
    }
}